const express = require("express");
const authRoutes = require("./auth.routes");
const jobRoutes = require("./job.routes");
const categoryRoutes = require("./category.routes");
const providerRoutes = require("./provider.routes");
const adminRoutes = require("./admin.routes");
const supplierRoutes = require("./supplier.routes");
const storeRoutes = require("./store.routes");
const paymentRoutes = require("./payment.routes");
const materialOrderRoutes = require("./materialOrder.routes");
const notificationRoutes = require("./notification.routes");
const specialRoutes = require("./special.routes");
const userRoutes = require("./user.routes");
const fileRoutes = require("./file.routes");
const geocodeRoutes = require("./geocode.routes");
const routingRoutes = require("./routing.routes");
const providerAccountRoutes = require("./providerAccount.routes");
const supplierPortalRoutes = require("./supplierPortal.routes");
const materialRoutes = require("./material.routes");
const ordersRoutes = require("./orders.routes");
const trackingRoutes = require("./tracking.routes");
const ratingRoutes = require("./rating.routes");
const providerReviewRoutes = require("./providerReview.routes");
const branchRoutes = require("./branch.routes");
const deliveryRequestRoutes = require("./deliveryRequest.routes");
const legalRoutes = require("./legal.routes");
const disputeRoutes = require("./dispute.routes");
const fraudRoutes = require("./fraud.routes");
const contactRoutes = require("./contact.routes");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/legal", legalRoutes);
router.use("/contact", contactRoutes);
router.use("/geocode", geocodeRoutes);
router.use("/routing", routingRoutes);
router.use("/jobs", jobRoutes);
router.use("/categories", categoryRoutes);
router.use("/providers", providerRoutes);
router.use("/admin", adminRoutes);
router.use("/suppliers", supplierRoutes);
router.use("/branches", branchRoutes);
router.use("/stores", storeRoutes);
router.use("/payments", paymentRoutes);
router.use("/material-orders", materialOrderRoutes);
router.use("/delivery-requests", deliveryRequestRoutes);
router.use("/orders", ordersRoutes);
router.use("/notifications", notificationRoutes);
router.use("/specials", specialRoutes);
router.use("/users", userRoutes);
router.use("/files", fileRoutes);
router.use("/provider", providerAccountRoutes);
router.use("/supplier", supplierPortalRoutes);
router.use("/materials", materialRoutes);
router.use("/tracking", trackingRoutes);
router.use("/ratings", ratingRoutes);
router.use("/provider-reviews", providerReviewRoutes);
router.use("/disputes", disputeRoutes);
router.use("/fraud", fraudRoutes);

module.exports = router;
